import numpy as np

r = np.random.exponential(5,500)
brightness = np.random.uniform(0.2, 1.0, 500)
brightness2 = np.random.uniform(0.2, 1.0, 500)
center_r = np.random.exponential(1,1000)
center_angle = np.random.uniform(0,2 * np.pi, 1000)
angle = r * 0.5 + np.random.normal(0,0.15,500)
x = r * np.cos(angle)
y = r * np.sin(angle)
print(x)
print(y)
x2 = r * np.cos(angle + np.pi)
y2 = r * np.sin(angle + np.pi)
print(x2)
print(y2)
center_x = center_r * np.cos(center_angle)
center_y = center_r * np.sin(center_angle)

import matplotlib.pyplot as plt
plt.scatter(x,y,s=2, alpha=brightness)
plt.scatter(x2,y2,s=2, alpha=brightness2)
plt.scatter(center_x, center_y,s=4, alpha=0.4)
plt.scatter(center_x, center_y,s=12, alpha=0.05)
plt.show()